spring:
  application:
    name: CloudConfig
  cloud:
    config:
      server:
        git:
          uri: ${uri}
                #          uri: https://github.com/PaaS-TA/SPRING-CLOUD-SAMPLE-CONFIG.git
          force-pull: true

server:
  port: ${PORT:8004}

management:
  security:
    enabled: false
