apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-deployment
  labels:
    app: cloud-config
  namespace: paas-0a9411c7-bf40-4b2f-9dcc-1d5acf24096e-caas 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
      - name: cloud-config
        image: syban/cloud-config:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8004
        env:
        - name: uri
          value: https://github.com/infranics/SPRING-CLOUD-SAMPLE-CONFIG.git
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-deployment
  labels:
    app: cloud-config
  namespace: paas-0a9411c7-bf40-4b2f-9dcc-1d5acf24096e-caas 
spec:
  ports:
  - port: 8004
    protocol: TCP
    targetPort: 8004
  selector:
    app: cloud-config
  type: NodePort
