apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-ui-deployment
  labels:
    app: cloud-ui
  namespace: paas-0a9411c7-bf40-4b2f-9dcc-1d5acf24096e-caas 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-ui
  template:
    metadata:
      labels:
        app: cloud-ui
    spec:
      containers:
      - name: cloud-ui
        image: syban/cloud-ui:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: config-domain
          value: cloud-config-deployment.paas-0a9411c7-bf40-4b2f-9dcc-1d5acf24096e-caas.svc.cluster.local
        - name: eureka-domain
          value: cloud-eureka-deployment.paas-0a9411c7-bf40-4b2f-9dcc-1d5acf24096e-caas.svc.cluster.local
        - name: SPRING_CLOUD_CLIENT_HOSTNAME
          value: cloud-ui-deployment.paas-0a9411c7-bf40-4b2f-9dcc-1d5acf24096e-caas.svc.cluster.local
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-ui-deployment
  labels:
    app: cloud-ui
  namespace: paas-0a9411c7-bf40-4b2f-9dcc-1d5acf24096e-caas 
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloud-ui
  type: NodePort
