apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-ui-deployment
  labels:
    app: cloud-ui
  namespace: paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-ui
  template:
    metadata:
      labels:
        app: cloud-ui
    spec:
      containers:
      - name: cloud-ui
        image: paastacp/cloud-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: config-domain
          value: cloud-config-deployment.paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas.svc.cluster.local
        - name: eureka-domain
          value: cloud-eureka-deployment.paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas.svc.cluster.local
        - name: redis-domain
          value: my-redis.paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas.svc.cluster.local
        - name: redis-port
          value: "6379"
      imagePullSecrets:
        - name: cp-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-ui-deployment
  labels:
    app: cloud-ui
  namespace: paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas
spec:
  ports:
  - nodePort: 32080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloud-ui
  type: NodePort
