apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-deployment
  labels:
    app: cloud-config
  namespace: paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
      - name: cloud-config
        image: infranics/cloud_config:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8004
        env:
        - name: uri
          value: https://github.com/infranics/SPRING-CLOUD-SAMPLE-CONFIG.git
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-deployment
  labels:
    app: cloud-config
  namespace: paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas
spec:
  ports:
  - nodePort: 31004
    port: 8004
    protocol: TCP
    targetPort: 8004
  selector:
    app: cloud-config
  type: NodePort
