apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-zuul-deployment
  labels:
    app: cloud-zuul
  namespace: paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-zuul
  template:
    metadata:
      labels:
        app: cloud-zuul
    spec:
      containers:
      - name: cloud-zuul
        image: infranics/cloud_zuul:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 2226
        env:
        - name: config-domain
          value: cloud-config-deployment.paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas.svc.cluster.local
        - name: eureka-domain
          value: cloud-eureka-deployment.paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas.svc.cluster.local
        - name: SPRING_CLOUD_CLIENT_HOSTNAME
          value: cloud-zuul-deployment.paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas.svc.cluster.local
        resources:
          limits:
            cpu: 150m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-zuul-deployment
  labels:
    app: cloud-zuul
  namespace: paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas
spec:
  ports:
  - nodePort: 32226
    port: 2226
    protocol: TCP
    targetPort: 2226
  selector:
    app: cloud-zuul
  type: NodePort
