apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-api-one-deployment
  labels:
    app: cloud-api-one
  namespace: paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-api-one
  template:
    metadata:
      labels:
        app: cloud-api-one
    spec:
      containers:
      - name: cloud-api-one
        image: infranics/cloud-api-one:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 2224
        env:
        - name: config-domain
          value: cloud-config-deployment.paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas.svc.cluster.local
        - name: eureka-domain
          value: cloud-eureka-deployment.paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas.svc.cluster.local
        - name: SPRING_CLOUD_CLIENT_HOSTNAME
          value: cloud-api-one-deployment.paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas.svc.cluster.local
        resources:
          limits:
            cpu: 150m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-api-one-deployment
  labels:
    app: cloud-api-one
  namespace: paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas
spec:
  ports:
  - port: 2224
    protocol: TCP
    targetPort: 2224
  selector:
    app: cloud-api-one
  type: NodePort
