apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-api-two-deployment
  labels:
    app: cloud-api-two
  namespace: paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-api-two
  template:
    metadata:
      labels:
        app: cloud-api-two
    spec:
      containers:
      - name: cloud-api-two
        image: infranics/cloud_api_two:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 2225
        env:
        - name: config-domain
          value: cloud-config-deployment.paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas.svc.cluster.local
        - name: eureka-domain
          value: cloud-eureka-deployment.paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas.svc.cluster.local
        - name: SPRING_CLOUD_CLIENT_HOSTNAME
          value: cloud-api-two-deployment.paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas.svc.cluster.local
        resources:
          limits:
            cpu: 150m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-api-two-deployment
  labels:
    app: cloud-api-two
  namespace: paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas
spec:
  ports:
  - port: 2225
    protocol: TCP
    targetPort: 2225
  selector:
    app: cloud-api-two
  type: NodePort
