apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-admin-deployment
  labels:
    app: cloud-admin
  namespace: paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-admin
  template:
    metadata:
      labels:
        app: cloud-admin
    spec:
      containers:
      - name: cloud-admin
        image: paastacp/cloud-admin
        imagePullPolicy: Always
        ports:
        - containerPort: 2223
        env:
        - name: config-domain
          value: cloud-config-deployment.paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas.svc.cluster.local
        - name: eureka-domain
          value: cloud-eureka-deployment.paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas.svc.cluster.local
        - name: SPRING_CLOUD_CLIENT_HOSTNAME
          value: cloud-admin-deployment.paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-admin-deployment
  labels:
    app: cloud-admin
  namespace: paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas
spec:
  ports:
  - nodePort: 32223
    port: 2223
    protocol: TCP
    targetPort: 2223
  selector:
    app: cloud-admin
  type: NodePort
