apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-ui-deployment
  labels:
    app: cloud-ui
  namespace: paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-ui
  template:
    metadata:
      labels:
        app: cloud-ui
    spec:
      containers:
      - name: cloud-ui
        image: infranics/cloud_ui:0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: config-domain
          value: cloud-config-deployment.paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas.svc.cluster.local
        - name: eureka-domain
          value: cloud-eureka-deployment.paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas.svc.cluster.local
        - name: SPRING_CLOUD_CLIENT_HOSTNAME
          value: cloud-ui-deployment.paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas.svc.cluster.local
        resources:
          limits:
            cpu: 150m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-ui-deployment
  labels:
    app: cloud-ui
  namespace: paas-e91b5f71-661c-4d4c-b136-571036eb0a31-caas
spec:
  ports:
  - nodePort: 32080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloud-ui
  type: NodePort
