apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-api-one-deployment
  labels:
    app: cloud-api-one
  namespace: paas-0a9411c7-bf40-4b2f-9dcc-1d5acf24096e-caas 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-api-one
  template:
    metadata:
      labels:
        app: cloud-api-one
    spec:
      containers:
      - name: cloud-api-one
        image: syban/cloud-api-one:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 2224
        env:
        - name: config-domain
          value: cloud-config-deployment.paas-0a9411c7-bf40-4b2f-9dcc-1d5acf24096e-caas.svc.cluster.local
        - name: eureka-domain
          value: cloud-eureka-deployment.paas-0a9411c7-bf40-4b2f-9dcc-1d5acf24096e-caas.svc.cluster.local
        - name: SPRING_CLOUD_CLIENT_HOSTNAME
          value: cloud-api-one-deployment.paas-0a9411c7-bf40-4b2f-9dcc-1d5acf24096e-caas.svc.cluster.local
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-api-one-deployment
  labels:
    app: cloud-api-one
  namespace: paas-0a9411c7-bf40-4b2f-9dcc-1d5acf24096e-caas 
spec:
  ports:
  - port: 2224
    protocol: TCP
    targetPort: 2224
  selector:
    app: cloud-api-one
  type: NodePort
