apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-eureka-deployment
  labels:
    app: cloud-eureka
  namespace: paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-eureka
  template:
    metadata:
      labels:
        app: cloud-eureka
    spec:
      containers:
      - name: cloud-eureka
        image: paastacp/cloud-eureka:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2221
        env:
        - name: config-domain
          value: cloud-config-deployment.paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas.svc.cluster.local
        - name: eureka-domain
          value: cloud-eureka-deployment.paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas.svc.cluster.local
      imagePullSecrets:
        - name: cp-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-eureka-deployment
  labels:
    app: cloud-eureka
  namespace: paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas
spec:
  ports:
  - nodePort: 32221
    port: 2221
    protocol: TCP
    targetPort: 2221
  selector:
    app: cloud-eureka
  type: NodePort
